apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::582921950567:role/eks_dashapp_role
      username: eks_dashapp_role
      groups:
        - system:masters
